"""create base tables

Revision ID: 09c96fd0e48f
Revises: 
Create Date: 2017-09-24 13:31:39.329342

"""
from alembic import op
import sqlalchemy as sa
import dutch_rare_breeds

# revision identifiers, used by Alembic.
revision = '09c96fd0e48f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', dutch_rare_breeds.lib.db.model.meta.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', dutch_rare_breeds.lib.db.model.meta.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_factors',
    sa.Column('id', dutch_rare_breeds.lib.db.model.meta.UUID(), nullable=False),
    sa.Column('species', dutch_rare_breeds.lib.db.model.meta.UUID(), nullable=True),
    sa.Column('breed', dutch_rare_breeds.lib.db.model.meta.UUID(), nullable=True),
    sa.Column('factor_one', sa.Integer(), nullable=True),
    sa.Column('factor_two', sa.Integer(), nullable=True),
    sa.Column('factor_three', sa.Integer(), nullable=True),
    sa.Column('factor_four', sa.Integer(), nullable=True),
    sa.Column('factor_five', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['breed'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['species'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_factors')
    op.drop_table('species')
    op.drop_table('breeds')
    # ### end Alembic commands ###
