"""column length improved

Revision ID: 21c638155ff4
Revises: de23b2029b49
Create Date: 2017-10-19 19:42:33.905597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c638155ff4'
down_revision = 'de23b2029b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
