"""comfirmed_default_true

Revision ID: 3b97fe3333c5
Revises: 2e00d812e406
Create Date: 2017-09-29 22:59:18.521703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b97fe3333c5'
down_revision = '2e00d812e406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_factors', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('risk_factors', 'confirmation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_factors', sa.Column('confirmation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('risk_factors', 'confirmed')
    # ### end Alembic commands ###
