"""change breed name length

Revision ID: de23b2029b49
Revises: 0e3d31371a8b
Create Date: 2017-10-19 19:11:26.967799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de23b2029b49'
down_revision = '0e3d31371a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
